### ISSUE TITLE
Attempt to subtract with overflow error

### ISSUE THREAD

**Issue by theduke** [atomashpolskiy/rustface#17] opened 2019-06-15 20:20 UTC
Hey, I'm getting a `Attempt to subtract with overflow` error on some images.

One such file is attached below.

Code:

```rust

const MODEL_SEETA_FD_FRONTAL: &'static [u8] = include_bytes!("./seeta_fd_frontal_v1.0.bin");


fn face_detector() -> Box<rustface::Detector> {
    let model = rustface::read_model(MODEL_SEETA_FD_FRONTAL.to_vec()).unwrap();
    rustface::create_detector_with_model(model)
}

pub fn face_detect<P>(
    path: P
) -> Result<Option<image::DynamicImage>, failure::Error>
    where P: AsRef<std::path::Path>
{
    use image::Pixel;

    let path = path.as_ref();

    let mut detector = face_detector();

    // Load the image.
    let mut image: image::DynamicImage = image::open(path)?;

    //        let rgb = image.clone().to_rgb();
    let gray = image.to_luma();
    let (width, height) = gray.dimensions();
    let mut grey_image = rustface::ImageData::new(gray.as_ptr(), width, height);
    let mut faces = detector.detect(&mut grey_image);

    dbg!(("Detected faces in image", &path, &faces,));

    if faces.len() == 1 {
        let info = faces.get(0).unwrap();
        let grid = &info.bbox();
        // Detected exactly one face!
        let face_image = image.crop(
            grid.x() as u32,
            grid.y() as u32,
            grid.width() as u32,
            grid.height() as u32,
        );

        Ok(Some(image))
    } else {
        Ok(None)
    }
}
```

Backtrace:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.2/src/math/mod.rs:56:31
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:212
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:382
   8: rust_begin_unwind
             at src/libstd/panicking.rs:309
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: rustface::math::vector_sub
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.2/src/math/mod.rs:56
  12: rustface::feat::surf_mlp_featmap::SurfMlpFeatureMap::compute_grad_y::{{closure}}
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rustface-0.1.2/src/feat/surf_mlp_featmap.rs:153
  13: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter::{{closure}}
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/for_each.rs:55
  14: core::iter::traits::iterator::Iterator::fold::{{closure}}
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libcore/iter/traits/iterator.rs:1685
  15: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libcore/iter/traits/iterator.rs:1573
  16: core::iter::traits::iterator::Iterator::fold
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libcore/iter/traits/iterator.rs:1685
  17: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/for_each.rs:55
  18: rayon::iter::plumbing::Producer::fold_with
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:110
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:438
  20: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.1.0/src/iter/plumbing/mod.rs:427
  21: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/join/mod.rs:127
  22: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::{{closure}}
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/job.rs:115
  23: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libstd/panic.rs:309
  24: std::panicking::try::do_call
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libstd/panicking.rs:294
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  26: std::panicking::try
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libstd/panicking.rs:273
  27: std::panic::catch_unwind
             at /rustc/5f3656ce9a2212fad872605b7a4ee103a155e9f3/src/libstd/panic.rs:388
  28: rayon_core::unwind::halt_unwinding
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/unwind.rs:17
  29: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/job.rs:115
  30: rayon_core::job::JobRef::execute
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/job.rs:59
  31: rayon_core::registry::WorkerThread::execute
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:734
  32: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:718
  33: rayon_core::registry::WorkerThread::wait_until
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:692
  34: rayon_core::registry::main_loop
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:812
  35: rayon_core::registry::ThreadBuilder::run
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:58
  36: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/theduke/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.5.0/src/registry.rs:103
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test detect::detect_faces ... FAILED
```

![twitch_preview_1](https://user-images.githubusercontent.com/241621/59555987-baf84580-8fbb-11e9-9bc7-abea595ff26a.jpg)

**Comment by jjhbw** [comment] 2019-06-16 11:55
Weird, I haven't been able to reproduce this using the image you provided. I'm using the latest stable toolchain:
```
active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.35.0 (3c235d560 2019-05-20)
```

Can you double-check your platform and toolchain?

**Comment by theduke** [comment] 2019-06-16 16:56
Toolchain: `rustc 1.37.0-nightly (5f3656ce9 2019-06-11)`
Arch Linux

**Comment by jjhbw** [comment] 2019-06-16 19:09
Couldn't get it to reproduce on macOS using`rustc 1.37.0-nightly (0dc9e9c10 2019-06-15)`. 

- Can you try with the same latest nightly?
- Maybe Github preprocessed the image you sent in a certain way ?

I used this code, derived from your example:
```rust
extern crate image;
extern crate failure;

const MODEL_SEETA_FD_FRONTAL: &'static [u8] = include_bytes!("../model/seeta_fd_frontal_v1.0.bin");

fn face_detector() -> Box<rustface::Detector> {
    let model = rustface::read_model(MODEL_SEETA_FD_FRONTAL.to_vec()).unwrap();
    rustface::create_detector_with_model(model)
}

fn main() {

    let path = "./59555987-baf84580-8fbb-11e9-9bc7-abea595ff26a.jpg";

    let mut detector = face_detector();

    // Load the image.
    let image: image::DynamicImage = image::open(path).unwrap();

    //        let rgb = image.clone().to_rgb();
    let gray = image.to_luma();
    let (width, height) = gray.dimensions();
    let mut grey_image = rustface::ImageData::new(gray.as_ptr(), width, height);
    let faces = detector.detect(&mut grey_image);

    dbg!(("Detected faces in image", &path, &faces,));
}

```

**Comment by jjhbw** [comment] 2020-09-08 05:23
Closing because I couldn't reproduce it. Feel free to reopen.

**Closed as completed by jjhbw** 2020-09-08 05:23 UTC
